blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.bu_login, name='login'),
    path('logout/', views.bu_logout, name='logout'),
    path('like/<int:post_id>/', views.like, name='like'),
    path('unlike/<int:post_id>/', views.unlike, name='unlike'),
    path('post_detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('admin/', views.admin, name='admin'),
    path('admin/posts/', views.admin_posts, name='admin_posts'),
    path('admin/post/<int:post_id>/', views.admin_post_detail, name='admin_post_detail'),
    path('admin/post/create/', views.create_post, name='create_post'),
    path('admin/post/edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('admin/post/delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('admin/comment/show/<int:comment_id>/', views.hide_comment, name='hide_comment'),
    path('admin/comment/hide/<int:comment_id>/', views.show_comment, name='show_comment'),
    path('admin/user/', views.admin_user, name='admin_user'),
    path('admin/user/create/', views.create_user, name='create_user'),
    path('admin/user/<str:username>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/login/', views.admin_login, name='admin_login'),
]

entry_task/urls.py
from django.contrib import admin
from django.urls import include, path

from blogs import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    post_title = models.CharField(max_length=30, unique=True)
    post_content = models.CharField(max_length=2500)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post_title

    class Meta:
        ordering = ('post_title',)


class BlogUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matric_no = models.CharField(max_length=9, unique=True, default="")
    liked_posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    class Meta:
        ordering = ('user__last_name',)


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_content = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_hidden = models.BooleanField(default=False)

    def __str__(self):
        return str(self.comment_id)

blogs/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post


class BlogUserLoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.Form):
    comment_content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Input comment...',
        'rows': 3
    }))


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'post_content']
        widgets = {
            'post_content': forms.Textarea(attrs={
                'rows': 5
            })
        }


class EditPostForm(forms.Form):
    post_title = forms.CharField(max_length=30)
    post_content = forms.CharField(max_length=2500,
                                   widget=forms.Textarea(attrs={'rows': 5}))


class BlogUserCreationForm(forms.Form):
    first_name = forms.CharField(max_length=20,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=20,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirmation = forms.CharField(widget=forms.PasswordInput)
    matric_no = forms.CharField(min_length=9, max_length=9)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password and password_confirmation:
            if password != password_confirmation:
                raise forms.ValidationError(_("Please re-enter your password and password confirmation."))

blogs/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect

from .forms import BlogUserLoginForm, CommentForm, CreatePostForm, EditPostForm, BlogUserCreationForm
from .models import BlogUser, Comment, Post


def index(request):
    context = {
        'posts': Post.objects.annotate(
            visible_comments=Count('comment', filter=Q(comment__is_hidden=False))
        )
    }

    if request.user.is_authenticated:
        context['bu'] = get_object_or_404(BlogUser, user=request.user)
    else:
        context['user_form'] = BlogUserLoginForm()

    return render(request, 'blogs/index.html', context)


def bu_login(request):
    if request.method == 'POST':
        form = BlogUserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                messages.add_message(request, messages.SUCCESS, "Welcome back, {}!".format(user.first_name))
                return redirect('blogs:index')

        messages.add_message(request, messages.ERROR, "Incorrect username or password.")

    return redirect('blogs:index')


def bu_logout(request):
    logout(request)
    return redirect('blogs:index')


def like(request, post_id):
    bu = get_object_or_404(BlogUser, user=request.user)
    p = get_object_or_404(Post, post_id=post_id)
    if p not in bu.liked_posts.all():
        bu.liked_posts.add(p)
        bu.save()
    return HttpResponseRedirect(request.GET.get('next', '/'))


def unlike(request, post_id):
    bu = get_object_or_404(BlogUser, user=request.user)
    p = get_object_or_404(Post, post_id=post_id)
    if p in bu.liked_posts.all():
        bu.liked_posts.remove(p)
        bu.save()
    return HttpResponseRedirect(request.GET.get('next', '/'))


def post_detail(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            user = get_object_or_404(BlogUser, user=request.user)
            post = get_object_or_404(Post, post_id=post_id)
            comment_content = request.POST['comment_content']
            c = Comment(user=user, post=post, comment_content=comment_content)
            c.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully commented on this post!")
        else:
            messages.add_message(request, messages.ERROR,
                                 "Oops, it looks like your comment is invalid. Please try again!")

    post = get_object_or_404(Post, post_id=post_id)
    comments = post.comment_set.all().filter(is_hidden=False)

    context = {
        'comment_form': CommentForm(),
        'post': post,
        'visible_comments': comments
    }

    if request.user.is_authenticated:
        context['bu'] = get_object_or_404(BlogUser, user=request.user)
    else:
        context['user_form'] = BlogUserLoginForm()

    return render(request, 'blogs/post_details.html', context)


def search(request):
    query = request.GET.get("q")
    print(type(query))
    context = dict()

    try:
        results = Post.objects.filter(Q(post_title__icontains=query) | Q(post_content__icontains=query)).values()
        context['results'] = results
    except Post.DoesNotExist:
        context['results'] = None

    if request.user.is_authenticated:
        context['bu'] = get_object_or_404(BlogUser, user=request.user)
    else:
        context['user_form'] = BlogUserLoginForm()

    return render(request, 'blogs/search.html', context)


@staff_member_required(login_url='blogs:admin_login')
def admin(request):
    return redirect('blogs:admin_posts')


def admin_login(request):
    if request.user.is_authenticated and request.user.is_staff:
        return redirect('blogs:admin')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_staff:
            login(request, user)

        return redirect('blogs:admin')

    return render(request, 'blogs/admin_login.html')


@staff_member_required(login_url='blogs:admin_login')
def admin_posts(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    return render(request, 'blogs/admin_posts.html', {
        'posts': paginator.get_page(page)
    })


@staff_member_required(login_url='blogs:admin_login')
def admin_post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blogs/admin_post_detail.html', {'post': post})


@staff_member_required(login_url='blogs:admin_login')
def hide_comment(request, comment_id):
    c = get_object_or_404(Comment, pk=comment_id)

    if not c.is_hidden:
        c.is_hidden = True
        c.save()

    if 'blogs/admin/post/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_post_detail', post_id=c.post.post_id)
    elif 'blogs/admin/user/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_user_detail', username=c.user.user.username)


@staff_member_required(login_url='blogs:admin_login')
def show_comment(request, comment_id):
    c = get_object_or_404(Comment, pk=comment_id)

    if c.is_hidden:
        c.is_hidden = False
        c.save()

    if 'blogs/admin/post/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_post_detail', post_id=c.post.post_id)
    elif 'blogs/admin/user/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_user_detail', username=c.user.user.username)

    return redirect('blogs:admin_post_detail', c.post.post_id)


@staff_member_required(login_url='blogs:admin_login')
def create_post(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            post_title = request.POST['post_title']
            post_content = request.POST['post_content']
            p = Post(post_title=post_title, post_content=post_content)
            p.save()
            messages.add_message(request, messages.SUCCESS, "You have succesfully created a post!")
            return redirect('blogs:admin_posts')
        else:
            messages.add_message(request, messages.ERROR, "Invalid post title and post content.")

    return render(request, 'blogs/admin_create_post.html', {
        'create_post_form': CreatePostForm()
    })


@staff_member_required(login_url='blogs:admin_login')
def edit_post(request, post_id):
    if request.method == 'POST':
        form = EditPostForm(request.POST)
        if form.is_valid():
            p = get_object_or_404(Post, pk=post_id)
            p.post_title = request.POST['post_title']
            p.post_content = request.POST['post_content']
            p.save()
            messages.add_message(request, messages.SUCCESS, "You have succesfully edited a post!")
            return redirect('blogs:admin_posts')

        else:
            print(form.errors)
            messages.add_message(request, messages.ERROR, "Invalid post title and post content.")

    post = get_object_or_404(Post, pk=post_id)

    return render(request, 'blogs/admin_edit_post.html', {
        'edit_post_form': EditPostForm(initial={
            'post_title': post.post_title,
            'post_content': post.post_content,
        })
    })


@staff_member_required(login_url='blogs:admin_login')
def delete_post(request, post_id):
    if request.method == 'POST':
        get_object_or_404(Post, pk=post_id).delete()

    return redirect('blogs:admin_posts')


@staff_member_required(login_url='blogs:admin_login')
def admin_user(request):
    user_list = BlogUser.objects.all()
    paginator = Paginator(user_list, 5)

    page = request.GET.get('page')
    return render(request, 'blogs/admin_user.html', {
        'users': paginator.get_page(page)
    })


@staff_member_required(login_url='blogs:admin_login')
def admin_user_detail(request, username):
    return render(request, 'blogs/admin_user_detail.html', {
        'bu': get_object_or_404(BlogUser, user__username=username)
    })


@staff_member_required(login_url='blogs:admin_login')
def create_user(request):
    if request.method == 'POST':
        form = BlogUserCreationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                request.POST['username'],
                password=request.POST['password'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
            )
            user.save()

            bu = BlogUser(user=user, matric_no=request.POST['matric_no'])
            bu.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully registered a user!")
            return redirect('blogs:admin_user')
        else:
            messages.add_message(request, messages.ERROR, "Invalid entries.")

    return render(request, 'blogs/admin_create_user.html', {
        'create_user_form': BlogUserCreationForm()
    })

blogs/templates/blogs/admin_create_post.html
{% extends 'base_admin_posts.html' %}

{% block content %}
  {% include 'message.html' %}
  <div class="ui segment">
    <h2 class="ui center aligned header">New Post</h2>
    <form class="ui form" method="post" action="{% url 'blogs:create_post' %}">
      {% csrf_token %}
      <div class="field">
        <label>Post Title</label>
        {{ create_post_form.post_title }}
      </div>
      <div class="field">
        <label>Post Content</label>
        {{ create_post_form.post_content }}
      </div>
      <button class="ui right floated button" type="submit">Submit</button>
    </form>
  </div>
{% endblock %}

blogs/templates/blogs/admin_create_user.html
{% extends 'base_admin_user.html' %}

{% block content %}
  {% include 'message.html' %}
  <div class="ui segment">
    <h2 class="ui center aligned header">New User</h2>
    <form class="ui form" method="post" action="{% url 'blogs:create_user' %}">
      {% csrf_token %}
      <div class="field">
        <label>Name</label>
        <div class="two fields">
          <div class="field">
            {{ create_user_form.first_name }}
          </div>
          <div class="field">
            {{ create_user_form.last_name }}
          </div>
        </div>
      </div>
      <div class="field">
        <label>Username</label>
        {{ create_user_form.username }}
      </div>
      <div class="field">
        <label>Password</label>
        {{ create_user_form.password }}
      </div>
      <div class="field">
        <label>Password Confirmation</label>
        {{ create_user_form.password_confirmation }}
      </div>
      <div class="field">
        <label>Matriculation Number</label>
        {{ create_user_form.matric_no }}
      </div>
      <button class="ui right floated button" type="submit">Submit</button>
    </form>
  </div>
{% endblock %}

blogs/templates/blogs/admin_edit_post.html
{% extends 'base_admin_posts.html' %}

{% block content %}
  {% include 'message.html' %}
  <div class="ui segment">
    <h2 class="ui center aligned header">Edit Post</h2>
    <form class="ui form" method="post" action="">
      {% csrf_token %}
      <div class="field">
        <label>Post Title</label>
        {{ edit_post_form.post_title }}
      </div>
      <div class="field">
        <label>Post Content</label>
        {{ edit_post_form.post_content }}
      </div>
      <button class="ui right floated button" type="submit">Submit</button>
    </form>
  </div>
{% endblock %}

blogs/templates/blogs/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin Login</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static "blogs/admin.css" %}">
  <script src="{% static "blogs/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "blogs/semantic.min.js" %}"></script>
</head>
<body>
<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui header">Blog administration</h2>
    <form class="ui large form" method="post" action="{% url 'blogs:admin_login' %}">
      {% csrf_token %}
      <div class="ui stacked segment">
        <div class="field">
          <div class="ui left icon input">
            <i class="user icon"></i>
            <input type="text" name="username" placeholder="Username">
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <input type="password" name="password" placeholder="Password">
          </div>
        </div>
        <button class="ui fluid large submit button" type="submit">Login</button>
      </div>
    </form>
  </div>
</div>
</body>
</html>

blogs/templates/blogs/admin_post_detail.html
{% extends 'base_admin_posts.html' %}

{% block content %}
  <div class="row">
    <div class="ui segment">
      <h4 class="ui header">{{ post.post_title }}</h4>
      <p>{{ post.post_content }}</p>
    </div>
  </div>

  <div class="ui basic segment">
    <div class="ui grid container">
      {% for comment in post.comment_set.all %}
        <div class="fourteen wide column">
          <div class="ui feed">
            <div class="event">
              <div class="label">
                {% load static %}
                <img src="{% static 'blogs/oreo.jpg' %}" alt="Avatar">
              </div>
              <div class="content">
                <div class="summary">
                  {{ comment.user.user.first_name }} {{ comment.user.user.last_name }}
                  <div class="date">
                    {{ comment.timestamp }}
                  </div>
                  {% if comment.is_hidden %}
                    <div class="ui red horizontal label">Hidden</div>
                  {% endif %}
                </div>
                <div class="extra text">
                  {{ comment.comment_content }}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="two wide column">
          {% if comment.is_hidden %}
            <a class="ui primary button" href="{% url 'blogs:show_comment' comment.comment_id %}">Show</a>
          {% else %}
            <a class="ui primary button" href="{% url 'blogs:hide_comment' comment.comment_id %}">Hide</a>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/admin_posts.html
{% extends 'base_admin_posts.html' %}

{% block content %}
  <div class="row">
    {% include 'message.html' %}
    <div class="ui basic clearing segment">
      <a class="ui right floated primary button" href="{% url 'blogs:create_post' %}">Create</a>
    </div>
  </div>
  <div class="row">
    <div class="ui segment">
      <table class="ui unstackable celled table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Comment Count</th>
          <th>Created at</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
          <tr>
            <td data-label="Name">
              <a href="{% url 'blogs:admin_post_detail' post.post_id %}">
                {{ post.post_title }}
              </a>
            </td>
            <td data-label="Comment Count">
              {{ post.comment_set.count }}
            </td>
            <td data-label="Created at">
              {{ post.timestamp }}
            </td>
            <td data-label="Action">
              <div class="ui icon buttons">
                <a class="ui button" title="Edit" href="{% url 'blogs:edit_post' post.post_id %}">
                  <i class="edit icon"></i>
                </a>
                <form method="post" action="{% url 'blogs:delete_post' post.post_id %}">
                  {% csrf_token %}
                  <button class="delete-post ui button" title="Delete" type="submit">
                    <i class="trash icon"></i>
                  </button>
                </form>
              </div>
            </td>
          </tr>
        {% endfor %}
        {#        <div class="ui basic modal">#}
        {#          <div class="ui icon header">#}
        {#            <i class="archive icon"></i>#}
        {#            Delete Post#}
        {#          </div>#}
        {#          <div class="content">#}
        {#            <p>#}
        {#              We understand that you do not want this post anymore. Are you sure you want to delete this post?#}
        {#            </p>#}
        {#          </div>#}
        {#          <div class="actions">#}
        {#            <div class="ui basic cancel inverted button">#}
        {#              <i class="remove icon"></i>#}
        {#              I changed my mind#}
        {#            </div>#}
        {#            <div class="ui red ok inverted button">#}
        {#              <i class="checkmark icon"></i>#}
        {#              Go ahead and delete#}
        {#            </div>#}
        {#          </div>#}
        {#        </div>#}
        </tbody>
      </table>
      <div class="ui divider"></div>
      <div class="ui centered grid">
        <div class="center aligned column">
          <div class="ui compact menu">
            {% if posts.has_previous %}
              <a class="item" href="?page=1">
                1
              </a>
              <div class="disabled item">
                ...
              </div>
              <a class="item" href="?page={{ posts.previous_page_number }}">
                {{ posts.previous_page_number }}
              </a>
            {% endif %}

            <a class="active item">{{ posts.number }}</a>

            {% if posts.has_next %}
              <a class="item" href="?page={{ posts.next_page_number }}">
                {{ posts.next_page_number }}
              </a>
              <div class="disabled item">
                ...
              </div>
              <a class="item" href="?page={{ posts.paginator.num_pages }}">
                {{ posts.paginator.num_pages }}
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
      $('.delete-post').click(function () {
          $('.ui.basic.modal').modal('show');
      });
  </script>
{% endblock %}

blogs/templates/blogs/admin_user.html
{% extends 'base_admin_user.html' %}

{% block content %}
  <div class="row">
    {% include 'message.html' %}
    <div class="ui basic clearing segment">
      <a class="ui right floated primary button" href="{% url 'blogs:create_user' %}">
        Create
      </a>
    </div>
  </div>
  <div class="row">
    <div class="ui segment">
      <table class="ui unstackable celled table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Comment Count</th>
          <th>Registered at</th>
        </tr>
        </thead>
        <tbody>
        {% for bu in users %}
          <tr>
            <td data-label="Name">
              <a href="{% url 'blogs:admin_user_detail' bu.user.username %}">
                {{ bu.user.first_name }} {{ bu.user.last_name }}
              </a>
            </td>
            <td data-label="Comment Count">
              {{ bu.comment_set.count }}
            </td>
            <td data-label="Registered at">
              {{ bu.user.date_joined }}
            </td>
          </tr>
        {% endfor %}
        {#        <div class="ui basic modal">#}
        {#          <div class="ui icon header">#}
        {#            <i class="archive icon"></i>#}
        {#            Delete User#}
        {#          </div>#}
        {#          <div class="content">#}
        {#            <p>#}
        {#              Are you sure you want to unregister this user from the blog?#}
        {#            </p>#}
        {#          </div>#}
        {#          <div class="actions">#}
        {#            <div class="ui basic cancel inverted button">#}
        {#              <i class="remove icon"></i>#}
        {#              I changed my mind#}
        {#            </div>#}
        {#            <div class="ui red ok inverted button">#}
        {#              <i class="checkmark icon"></i>#}
        {#              Go ahead and delete#}
        {#            </div>#}
        {#          </div>#}
        {#        </div>#}
        </tbody>
      </table>
      <div class="ui divider"></div>
      <div class="ui centered grid">
        <div class="center aligned column">
          <div class="ui compact menu">
            {% if users.has_previous %}
              <a class="item" href="?page=1">
                1
              </a>
              <div class="disabled item">
                ...
              </div>
              <a class="item" href="?page={{ users.previous_page_number }}">
                {{ users.previous_page_number }}
              </a>
            {% endif %}

            <a class="active item">{{ users.number }}</a>

            {% if users.has_next %}
              <a class="item" href="?page={{ users.next_page_number }}">
                {{ users.next_page_number }}
              </a>
              <div class="disabled item">
                ...
              </div>
              <a class="item" href="?page={{ users.paginator.num_pages }}">
                {{ users.paginator.num_pages }}
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/admin_user_detail.html
{% extends 'base_admin_user.html' %}

{% block content %}
  <div class="row">
    <div class="ui segment">
      {% load static %}
      <h2 class="ui header">
        <img src="{% static "blogs/oreo.jpg" %}" alt="Avatar">
        <div class="content">
          {{ bu.user.first_name }} {{ bu.user.last_name }}
          <div class="sub header">{{ bu.matric_no }}</div>
        </div>
      </h2>
    </div>
  </div>

  <div class="ui basic segment">
    <div class="ui grid container">
      {% for comment in bu.comment_set.all %}
        <div class="fourteen wide column">
          <div class="ui feed">
            <div class="event">
              <div class="label">
                {% load static %}
                <img src="{% static 'blogs/oreo.jpg' %}" alt="Avatar">
              </div>
              <div class="content">
                <div class="summary">
                  {{ comment.user.user.first_name }} {{ comment.user.user.last_name }}
                  <div class="date">
                    {{ comment.timestamp }}
                  </div>
                  {% if comment.is_hidden %}
                    <div class="ui red horizontal label">Hidden</div>
                  {% endif %}
                </div>
                <div class="extra text">
                  {{ comment.comment_content }}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="two wide column">
          {% if comment.is_hidden %}
            <a class="ui primary button" href="{% url 'blogs:show_comment' comment.comment_id %}">Show</a>
          {% else %}
            <a class="ui primary button" href="{% url 'blogs:hide_comment' comment.comment_id %}">Hide</a>
          {% endif %}
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/index.html
{% extends "base_user.html" %}

{% load static %}

{% block posts %}
  {% for post in posts %}
    <div class="ui clearing segment">
      <div class="ui header">{{ post.post_title }}</div>
      <p>{{ post.post_content }}</p>
      <div>
        {% include "post_buttons.html" with comment_count=post.visible_comments %}
      </div>
    </div>
  {% endfor %}
{% endblock %}

{% block message_user_login %}
  {% include 'message.html' %}
{% endblock %}

{% block user %}
  {% include "user.html" %}
{% endblock %}

blogs/templates/blogs/post_details.html
{% extends "base_user.html" %}

{% block posts %}
  <div class="ui clearing segment">
    <div class="ui header">
      <div>{{ post.post_title }}</div>
    </div>
    <p>{{ post.post_content }}</p>
    <div>
      <div class="ui label">{{ post.timestamp }}</div>
      {% include "post_buttons.html" with comment_count=visible_comments.count %}
    </div>
  </div>
{% endblock %}

{% block comments %}
  {% include 'message.html' %}
  <div class="ui basic clearing segment">
    <form class="ui form" method="post" action="{% url 'blogs:post_detail' post.post_id %}">
      {% csrf_token %}
      <div class="field">
        <label>Comments</label>
        {{ comment_form.comment_content }}
      </div>
      {% if request.user.is_authenticated %}
        <button class="ui right floated button" type="submit">Submit</button>
      {% else %}
        <button class="ui right floated disabled button" type="submit">Submit</button>
      {% endif %}
    </form>
  </div>
  <div class="ui feed">
    {% for comment in visible_comments %}
      <div class="event">
        <div class="label">
          {% load static %}
          <img src="{% static 'blogs/oreo.jpg' %}" alt="Avatar">
        </div>
        <div class="content">
          <div class="summary">
            {{ comment.user.user.first_name }} {{ comment.user.user.last_name }}
            <div class="date">
              {{ comment.timestamp }}
            </div>
          </div>
          <div class="extra text">
            {{ comment.comment_content }}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

{% block user %}
  {% include "user.html" %}
{% endblock %}

blogs/templates/blogs/search.html
{% extends "base_user.html" %}

{% block posts %}
  {% if request.GET.q %}
    <h4 class="ui header">Search results for {{ request.GET.q }}:</h4>
  {% endif %}
  {% if results %}
    {% for post in results %}
      <div class="ui clearing segment">
        <div class="ui header">{{ post.post_title }}</div>
        <p>{{ post.post_content }}</p>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

{% block user %}
  {% include "user.html" %}
{% endblock %}