blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.bu_login, name='login'),
    path('logout/', views.bu_logout, name='logout'),
    path('like/<int:post_id>/', views.like, name='like'),
    path('unlike/<int:post_id>/', views.unlike, name='unlike'),
    path('post_detail/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('admin/', views.admin, name='admin'),
    path('admin/posts/', views.admin_posts, name='admin_posts'),
    path('admin/post/<int:post_id>/', views.admin_post_detail, name='admin_post_detail'),
    path('admin/post/create/', views.create_post, name='create_post'),
    path('admin/post/edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('admin/post/delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('admin/comment/show/<int:comment_id>/', views.hide_comment, name='hide_comment'),
    path('admin/comment/hide/<int:comment_id>/', views.show_comment, name='show_comment'),
    path('admin/user/', views.admin_user, name='admin_user'),
    path('admin/user/create/', views.create_user, name='create_user'),
    path('admin/user/<str:username>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/login/', views.admin_login, name='admin_login'),
]

entry_task/urls.py
from django.contrib import admin
from django.urls import include, path

from blogs import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    post_title = models.CharField(max_length=30, unique=True)
    post_content = models.CharField(max_length=2500)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post_title

    class Meta:
        ordering = ('post_title',)


class BlogUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matric_no = models.CharField(max_length=9, unique=True, default="")
    liked_posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    class Meta:
        ordering = ('user__last_name',)


class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_content = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_hidden = models.BooleanField(default=False)

    def __str__(self):
        return str(self.comment_id)

blogs/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post


class BlogUserLoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.Form):
    comment_content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder': 'Input comment...',
        'rows': 3
    }))


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title', 'post_content']
        widgets = {
            'post_content': forms.Textarea(attrs={
                'rows': 5
            })
        }


class EditPostForm(forms.Form):
    post_title = forms.CharField(max_length=30)
    post_content = forms.CharField(max_length=2500,
                                   widget=forms.Textarea(attrs={'rows': 5}))


class BlogUserCreationForm(forms.Form):
    first_name = forms.CharField(max_length=20,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=20,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirmation = forms.CharField(widget=forms.PasswordInput)
    matric_no = forms.CharField(min_length=9, max_length=9)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password and password_confirmation:
            if password != password_confirmation:
                raise forms.ValidationError(_("Please re-enter your password and password confirmation."))

blogs/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect

from .forms import BlogUserLoginForm, CommentForm, CreatePostForm, EditPostForm, BlogUserCreationForm
from .models import BlogUser, Comment, Post


def index(request):
    context = {
        'posts': Post.objects.annotate(
            visible_comments=Count('comment', filter=Q(comment__is_hidden=False))
        )
    }

    if request.user.is_authenticated:
        context['bu'] = get_object_or_404(BlogUser, user=request.user)
    else:
        context['user_form'] = BlogUserLoginForm()

    return render(request, 'blogs/index.html', context)


def bu_login(request):
    if request.method == 'POST':
        form = BlogUserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                messages.add_message(request, messages.SUCCESS, "Welcome back, {}!".format(user.first_name))
                return redirect('blogs:index')

        messages.add_message(request, messages.ERROR, "Incorrect username or password.")

    return redirect('blogs:index')


def bu_logout(request):
    logout(request)
    return redirect('blogs:index')


def like(request, post_id):
    bu = get_object_or_404(BlogUser, user=request.user)
    p = get_object_or_404(Post, post_id=post_id)
    if p not in bu.liked_posts.all():
        bu.liked_posts.add(p)
        bu.save()
    return HttpResponseRedirect(request.GET.get('next', '/'))


def unlike(request, post_id):
    bu = get_object_or_404(BlogUser, user=request.user)
    p = get_object_or_404(Post, post_id=post_id)
    if p in bu.liked_posts.all():
        bu.liked_posts.remove(p)
        bu.save()
    return HttpResponseRedirect(request.GET.get('next', '/'))


def post_detail(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            user = get_object_or_404(BlogUser, user=request.user)
            post = get_object_or_404(Post, post_id=post_id)
            comment_content = request.POST['comment_content']
            c = Comment(user=user, post=post, comment_content=comment_content)
            c.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully commented on this post!")
        else:
            messages.add_message(request, messages.ERROR,
                                 "Oops, it looks like your comment is invalid. Please try again!")

    post = get_object_or_404(Post, post_id=post_id)
    comments = post.comment_set.all().filter(is_hidden=False)

    context = {
        'comment_form': CommentForm(),
        'post': post,
        'visible_comments': comments
    }

    if request.user.is_authenticated:
        context['bu'] = get_object_or_404(BlogUser, user=request.user)
    else:
        context['user_form'] = BlogUserLoginForm()

    return render(request, 'blogs/post_details.html', context)


def search(request):
    query = request.GET.get("q")
    print(type(query))
    context = dict()

    try:
        results = Post.objects.filter(Q(post_title__icontains=query) | Q(post_content__icontains=query)).values()
        context['results'] = results
    except Post.DoesNotExist:
        context['results'] = None

    if request.user.is_authenticated:
        context['bu'] = get_object_or_404(BlogUser, user=request.user)
    else:
        context['user_form'] = BlogUserLoginForm()

    return render(request, 'blogs/search.html', context)


@staff_member_required(login_url='blogs:admin_login')
def admin(request):
    return redirect('blogs:admin_posts')


def admin_login(request):
    if request.user.is_authenticated and request.user.is_staff:
        return redirect('blogs:admin')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_staff:
            login(request, user)

        return redirect('blogs:admin')

    return render(request, 'blogs/admin_login.html')


@staff_member_required(login_url='blogs:admin_login')
def admin_posts(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    return render(request, 'blogs/admin_posts.html', {
        'posts': paginator.get_page(page)
    })


@staff_member_required(login_url='blogs:admin_login')
def admin_post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blogs/admin_post_detail.html', {'post': post})


@staff_member_required(login_url='blogs:admin_login')
def hide_comment(request, comment_id):
    c = get_object_or_404(Comment, pk=comment_id)

    if not c.is_hidden:
        c.is_hidden = True
        c.save()

    if 'blogs/admin/post/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_post_detail', post_id=c.post.post_id)
    elif 'blogs/admin/user/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_user_detail', username=c.user.user.username)


@staff_member_required(login_url='blogs:admin_login')
def show_comment(request, comment_id):
    c = get_object_or_404(Comment, pk=comment_id)

    if c.is_hidden:
        c.is_hidden = False
        c.save()

    if 'blogs/admin/post/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_post_detail', post_id=c.post.post_id)
    elif 'blogs/admin/user/' in request.META['HTTP_REFERER']:
        return redirect('blogs:admin_user_detail', username=c.user.user.username)

    return redirect('blogs:admin_post_detail', c.post.post_id)


@staff_member_required(login_url='blogs:admin_login')
def create_post(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            post_title = request.POST['post_title']
            post_content = request.POST['post_content']
            p = Post(post_title=post_title, post_content=post_content)
            p.save()
            messages.add_message(request, messages.SUCCESS, "You have succesfully created a post!")
            return redirect('blogs:admin_posts')
        else:
            messages.add_message(request, messages.ERROR, "Invalid post title and post content.")

    return render(request, 'blogs/admin_create_post.html', {
        'create_post_form': CreatePostForm()
    })


@staff_member_required(login_url='blogs:admin_login')
def edit_post(request, post_id):
    if request.method == 'POST':
        form = EditPostForm(request.POST)
        if form.is_valid():
            p = get_object_or_404(Post, pk=post_id)
            p.post_title = request.POST['post_title']
            p.post_content = request.POST['post_content']
            p.save()
            messages.add_message(request, messages.SUCCESS, "You have succesfully edited a post!")
            return redirect('blogs:admin_posts')

        else:
            print(form.errors)
            messages.add_message(request, messages.ERROR, "Invalid post title and post content.")

    post = get_object_or_404(Post, pk=post_id)

    return render(request, 'blogs/admin_edit_post.html', {
        'edit_post_form': EditPostForm(initial={
            'post_title': post.post_title,
            'post_content': post.post_content,
        })
    })


@staff_member_required(login_url='blogs:admin_login')
def delete_post(request, post_id):
    if request.method == 'POST':
        get_object_or_404(Post, pk=post_id).delete()

    return redirect('blogs:admin_posts')


@staff_member_required(login_url='blogs:admin_login')
def admin_user(request):
    user_list = BlogUser.objects.all()
    paginator = Paginator(user_list, 5)

    page = request.GET.get('page')
    return render(request, 'blogs/admin_user.html', {
        'users': paginator.get_page(page)
    })


@staff_member_required(login_url='blogs:admin_login')
def admin_user_detail(request, username):
    return render(request, 'blogs/admin_user_detail.html', {
        'bu': get_object_or_404(BlogUser, user__username=username)
    })


@staff_member_required(login_url='blogs:admin_login')
def create_user(request):
    if request.method == 'POST':
        form = BlogUserCreationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                request.POST['username'],
                password=request.POST['password'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
            )
            user.save()

            bu = BlogUser(user=user, matric_no=request.POST['matric_no'])
            bu.save()
            messages.add_message(request, messages.SUCCESS, "You have successfully registered a user!")
            return redirect('blogs:admin_user')
        else:
            messages.add_message(request, messages.ERROR, "Invalid entries.")

    return render(request, 'blogs/admin_create_user.html', {
        'create_user_form': BlogUserCreationForm()
    })

blogs/templates/base_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  {% block head %}
    <title>My Cool Blog - Admin</title>
  {% endblock %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static "blogs/user.css" %}">
  <script src="{% static "blogs/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "blogs/semantic.min.js" %}"></script>
</head>
<body>
<div class="ui grid container">
  <div class="four wide column">
    {% block nav %}
    {% endblock %}
  </div>
  <div class="twelve wide column">
    {% block content %}
    {% endblock %}
  </div>
</div>
{% block script %}
{% endblock %}
</body>
</html>

blogs/templates/base_admin_posts.html
{% extends 'base_admin.html' %}

{% block nav %}
  <div class="ui secondary vertical menu">
    <a class="active item">Posts</a>
    <a class="item" href="{% url 'blogs:admin_user' %}">User</a>
  </div>
{% endblock %}

blogs/templates/base_admin_user.html
{% extends 'base_admin.html' %}

{% block nav %}
  <div class="ui secondary vertical menu">
    <a class="item" href="{% url 'blogs:admin_posts' %}">Posts</a>
    <a class="active item">User</a>
  </div>
{% endblock %}

blogs/templates/base_user.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  {% block head %}
    <title>My Cool Blog</title>
  {% endblock %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
  {% load static %}
  <link rel="stylesheet" href="{% static "blogs/user.css" %}">
  <script src="{% static "blogs/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "blogs/semantic.min.js" %}"></script>
</head>
<body>
<div class="ui grid container">
  <a class="ui huge header" href="{% url 'blogs:index' %}">My Cool Blog</a>
  <div class="row">
    <div class="right aligned column">
      <form class="ui search" method="get" action="{% url 'blogs:search' %}">
        <div class="ui icon input">
          <input class="prompt" name="q" type="text" placeholder="Search...">
          <i class="search icon"></i>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="ten wide column">
      {% block posts %}
      {% endblock %}
      {% block comments %}
      {% endblock %}
    </div>
    <div class="six wide column">
      {% block message_user_login %}
      {% endblock %}
      <div class="ui segment">
        {% block user %}
        {% endblock %}
      </div>
    </div>
  </div>
</div>
</body>
</html>

blogs/templates/message.html
{% if messages %}
  {% for message in messages %}
    <div class="ui {% if message.tags %}{{ message.tags }}{% endif %} message">
    <i class="close icon"></i>
    {% if message.tags %}
      <div class="header">
        {{ message.tags|title }}
      </div>
    {% endif %}
    <p>{{ message }}</p>
  {% endfor %}
</div>
{% endif %}

{% block script %}
  <script>
      $('.message .close').on('click', function () {
          $(this).closest('.message').transition('fade');
      });
  </script>
{% endblock %}

blogs/templates/post_buttons.html
{% if request.user.is_authenticated %}
  <div class="ui right floated labeled button" tabindex="0">
    <a class="ui basic blue button" href="{% url 'blogs:post_detail' post.post_id %}">
      <i class="comments icon"></i> Comment
    </a>
    <a class="ui basic left pointing blue label">
      {{ comment_count }}
    </a>
  </div>
  <div class="ui right floated labeled button" tabindex="0">
    {% if bu in post.bloguser_set.all %}
      <a class="ui red button" href="{% url 'blogs:unlike' post.post_id %}?next={{ request.path }}">
        <i class="heart icon"></i> Like
      </a>
    {% else %}
      <a class="ui basic red button" href="{% url 'blogs:like' post.post_id %}?next={{ request.path }}">
        <i class="heart icon"></i> Like
      </a>
    {% endif %}
    <div class="ui basic red left pointing label">
      {{ post.bloguser_set.count }}
    </div>
  </div>
{% else %}
  <div class="ui disabled right floated labeled button" tabindex="0">
    <div class="ui basic blue button">
      <i class="comments icon"></i> Comment
    </div>
    <a class="ui basic left pointing blue label">
      {{ post.comment_set.count }}
    </a>
  </div>
  <div class="ui disabled right floated labeled button" tabindex="0">
    <div class="ui basic red button">
      <i class="heart icon"></i> Like
    </div>
    <a class="ui basic red left pointing label">
      {{ post.bloguser_set.count }}
    </a>
  </div>
{% endif %}

blogs/templates/user.html
{% if not request.user.is_authenticated %}
  <form class="ui form" action="{% url 'blogs:login' %}" method="post">
    {% csrf_token %}
    <div class="field">
      <label>Username</label>
      {{ user_form.username }}
    </div>
    <div class="field">
      <label>Password</label>
      {{ user_form.password }}
    </div>
    <button class="ui right floated button" type="submit">Login</button>
  </form>
{% else %}
  {% load static %}
  <h2 class="ui header">
    <img src="{% static "blogs/oreo.jpg" %}" alt="Avatar">
    <div class="content">
      {{ bu.user.first_name }} {{ bu.user.last_name }}
      <div class="sub header">{{ bu.matric_no }}</div>
    </div>
  </h2>
  <a class="ui right floated button" href="{% url 'blogs:logout' %}">Logout</a>
{% endif %}